"""
Given the environment:

|-[csv_files]
|   |- xxx.csv (autogenerated)
|-[text_files]
|   |- xxx.txt
|-[updates]
|   |- xxx.txt (autogenerated)
|-[tools]
|   |- (python files)
|
|-writeCSV.py
|-(Penny.concordance.xlsx) OR
|-(Penny.concordance.json)


All the .txt files in ./text_files will be processed (and run against a concordance, which looks up their Museum+ object number and catalogue number). If the concordance has already been created (i.e. there is a .json file, then this will be used to save time/effort.)

The result is output as an Excel file for upload to museum+
AND a .txt file including these two numbers for future reference (i.e. use without the concordance) is output in ./updates

Markup:
[One per line:]

@@META:PUB_DATE=DD/MM/YYYY
the publication date of the work

@@NEW:1 or 1&2&...
the section title or titles

@@PROCESS
Ignore any lines before this after encountering a @@NEW

[Inline commands:]

@@LINK: ... @@ -> e.g. @@LINK:No. 20@@
insert link text -- but currently not used. The markup is simply discarded, leaving the bare text inside untouched.
"""
from pathlib import Path
from tools import shared

from dataclasses import dataclass, field

# from typing import Iterable
import logging
import sys
import re
from collections import defaultdict
from copy import copy as shallow_copy

from pprint import pprint

logging.basicConfig(
    level=logging.INFO,
    format="%(levelname)s:%(message)s",
    handlers=[
        logging.FileHandler("textExtract.log", mode="w", encoding="utf-8"),
        logging.StreamHandler(sys.stdout)
    ],
)


@dataclass
class Overview:
    count: defaultdict[str, int] = field(default_factory=lambda: defaultdict(int))
    missing: defaultdict[str, list[int]] = field(
        default_factory=lambda: defaultdict(list)
    )

overview = Overview()

@dataclass
class Section:
    id: str
    oid: str
    onum: str
    paragraphs: list[str]


class Content:
    def __init__(self, pd: str, ps: dict, cl: list, line: str, csk: list, cinfo: dict, ci=True):
        self.pub_date: str = pd
        self.processed_sections: dict[str, Section] = ps
        self.current = Section("", "", "", [])
        self.line: str = line
        self.current_section_keys: list[str] = csk
        self.currently_ignoring: bool = ci

    def update_processed_sections(self):
        for key in self.current_section_keys:
            self.processed_sections[key] = shallow_copy(self.current)
        self.current = Section("", "", "", [])
        self.current_section_keys = []

    def start_new_section(self, new_section_keys: list[str]):
        self.update_processed_sections()
        self.current_section_keys = new_section_keys
        self.currently_ignoring = True

    def update_current_lines(self):
        if self.line:
            self.current.paragraphs.append(self.line)
            self.line = ""

    def add_to_line(self, part:str):
        # print(f">>>> {part[:50]}, {self.currently_ignoring}")
        if not self.currently_ignoring:
            self.line += part


@dataclass
class Command:
    verb: str
    object_list: list[str]


type ExcelRow = tuple[str, str, str, str, str, str, str, str, str, str, str, str, str]


def make_concordance_from_excel(excel_file_path:Path) -> dict[str, list[str]]:
    """
    concordance layout with example data:
    row 0*  1*                   2                           3                   4                       5 (key)        6 notes
    ObjID	ObjectNumber	    ObjectNumberSorted	        ReferenceNumber	    ObjectTitle	            PW:litCatNo
    742939	WA1947.191.176.1	WA1947.00191.00176.00001	Penny (1992) 1	    Flagellator of Christ	1

    PW:litCatNo (column 5) is the number given in the publication, so it is the key to the object id
    It takes the first worksheet regardless of name.
    It returns a dictionary: { section id : [museum+ object number, catalogue number]}
    """
    raw = shared.extract_from_excel(excel_file_path)
    concordance = normalise_concordance(raw)
    return concordance


def normalise_concordance(raw: list[list[str]]) -> dict[str, list[str]]:
    concordance: dict[str, list[str]] = {}
    for row in raw:
        object_id = row[0]
        object_num = row[1]
        key = row[5]
        if key.isnumeric():
            concordance[key] = [object_id, object_num]
    return concordance


def process(raw_lines: list[str], concordance: dict[str, list[str]]) -> Content:
    """
    This will replace group_lines(), get_command(), get_inline_commands() & parse_inline_command()
    This sorts the lines (paragraphs) into sections
    filters out lines that aren't needed
    and expands any inline commands
    """
    content: Content = Content("", {}, [], "", [],{})
    for raw_line in raw_lines:
        if not raw_line:
            continue
        phrases = chunk_by_command(raw_line)
        for _type, cmd, other in phrases:
            match _type:
                case "none":
                    content.add_to_line(other)
                case "V":
                    content = process_verb(cmd, content)
                case "VO":
                    content = process_verb_object(cmd, content, concordance)
                case "unknown":
                    msg = f">>>> UNKNOWN command: {cmd}"
                    logging.error(msg)
        content.update_current_lines()
    if content.current.paragraphs:
        content.update_processed_sections()
    if content.pub_date:
        logging.info(f"Pub date: {content.pub_date}")
    else:
        logging.critical("No publication date found!")
    return content


def chunk_by_command(line: str) -> list[tuple[str, Command, str]]:
    """
    Given a string with embedded commands, marked by @@
    returns a list
    """
    open_cmd = False
    output = []
    pre_parsed_line = [el for el in re.split(r"(@@)", line) if el]
    ## re group preserves "@@": allows it to be matched with command to distinguish "PROCESS" (text) vs "@@PROCESS" (cmd)
    for phrase in pre_parsed_line:
        if phrase == "@@":
            open_cmd = not open_cmd
            continue
        if open_cmd:
            _type, cmd, other = parse_command(phrase)
        else:
            _type = "none"
            cmd = Command("", [])
            other = phrase
            # print(f">>>> {phrase[:50]}")
        output.append((_type, cmd, other))
    return output


def parse_command(phrase: str) -> tuple[str, Command, str]:
    simple_commands = ["process", "ignore"]  # "@@CMD\n" or "@@CMD@@..."
    ## oid = object id; onum = object number
    compound_commands = ["meta", "link", "new", "oid", "onum"]  # "@@CMD:value@@"
    result: tuple[str, Command, str]    ## type, command, other
    if phrase.lower() in simple_commands:
        result = ("V", Command(phrase.lower(), []), "")
    elif re.search(r"^\d[\d& /,]*$", phrase):
        ## to catch alternative short form @@1&2 (= @@NEW:1&2)
        result = ("VO", Command("new", [phrase]), "")
    else:
        verb_object = phrase.split(":")
        if len(verb_object) == 1:
            result = ("unknown", Command("", []), "")
        else:
            verb, raw_object = verb_object
            verb = verb.lower()
            if verb in compound_commands:
                result = ("VO", Command(verb, raw_object.split("=")), "")
            else:
                result = ("none", Command("", []), phrase)
    return result


def process_verb(cmd: Command, content: Content) -> Content:
    match cmd.verb:
        case "ignore":
            content.currently_ignoring = True
        case "process":
            content.currently_ignoring = False
        case "unknown":
            msg = f"unknown verb ({cmd.object_list})"
            logging.warning(msg)
    overview.count[cmd.verb] += 1
    return content


def process_verb_object(cmd: Command, content: Content, concordance) -> Content:
    match cmd.verb:
        case "new":
            if (key_count := len(content.current_section_keys)) > 1:
                overview.count["EXTRA_sections"] += key_count - 1
            new_section_keys = [
                el for el in re.split(r"[\s&,]", cmd.object_list[0]) if el
            ]
            content.start_new_section(new_section_keys)
            content.currently_ignoring = True  ## ignore up to "process" in Penny
        case "meta":
            if cmd.object_list[0].lower() == "pub_date":
                # content.pub_date = cmd.object_list[1]
                date = cmd.object_list[1]
                date = date.replace("/", "-")
                date = date.replace(":", "-")
                content.pub_date = date
            else:
                msg = f"Unknown META value: {cmd.object_list}"
                logging.warning(msg)
        case "link":
            text = cmd.object_list[0]
            content.add_to_line(text)
            # content.line = text
            # currently, links are ignored, but see this possibility:
            # number = re.sub(r"[^\d]", "", text)
            # if number:
            #     ref = concordance.get(number, ["", ""])[1]
            #     content.line = f" [{ref}]" if ref else ""
        case "oid":
            content.current.oid = cmd.object_list[0]
        case "onum":
            content.current.onum = cmd.object_list[0]
        case _:
            msg = f"The command '{cmd.verb}' is unknown."
            logging.warning(msg)
    overview.count[cmd.verb] += 1
    return content


def create_shared_description_message(
    current_sections: list[str], concordance: dict[str, list[str]]
) -> str:
    shared_blurb = " & ".join(
        (
            f"{section} ({concordance.get(section, ("","UNKNOWN"))[1]})"
            for section in current_sections
        )
    )
    message = (
        f"[Description shared between {len(current_sections)} items: {shared_blurb}]"
    )
    logging.info(message)
    return message


def apply_concordance(content:Content, concordance: dict[str, list[str]]) -> Content:
    for num, section in content.processed_sections.items():
        if not section.oid:
            section.oid, section.onum = concordance.get(num, ["",""])
        if not section.oid:
            logging.warning(f"No object id found in concordance for record {num}.")
            overview.missing["from_concordance"].append(int(num))
    return content


def prepare_for_csv(
    content: Content,
    import_identifier: str,
    filter_by_id:list[str] | None = None,
) -> list[ExcelRow]:
    headings = (
        "ID",       # Museum+ id of the item described
        "Import identifier",  # name given to this batch operation
        "Audience", # Always 'Public'
        "Date",     # DD/MM/YYYY
        "Notes",
        "Purpose",
        "Sort",     # Always '100' in case of multiple entries
        "Source",
        "Status",   # Always '05 Published'
        "Text",
        "Title / Ref. No.",
        "Type",     # Always catalogue text
        "Language",
    )
    output: list[ExcelRow] = []
    object_id: str
    audience = "Public"  ## NB capital P
    purpose = ""
    _sort = "100"
    title = ""
    notes = ""
    source = ""
    # status = "05 Published"
    status = "" ## Laura's instructions for Penny (as unsure Ashmolean has publishing rights)
    _type = "catalogue text"
    language = "en"
    output.append(headings)
    for num, section in content.processed_sections.items():
        if filter_by_id and section.oid in filter_by_id:
            continue
        if section.oid:
            overview.count["records_output"] += 1
            text = "\n\n".join(section.paragraphs)
            output.append(
                (
                    section.oid,
                    import_identifier,
                    audience,
                    content.pub_date,
                    notes,
                    purpose,
                    _sort,
                    source,
                    status,
                    text,
                    title,
                    _type,
                    language,
                )
            )
        else:
            logging.critical(f"Record {num} excluded from csv output as it lacks an object ID.")
            # overview.missing["from_concordance"].append(int(num))
    return (output)


def overview_report() -> str:
    report = "*" * 70 + "\n"
    report += "\t** Overview of commands performed:\n"
    report += f"\t** {", ".join([f"{key}={val}" for key, val in overview.count.items()])}\n"
    report += f"\t** Each section included a 'process' statement: {overview.count["new"] == overview.count["process"]}\n"
    report += f"\t** Total number of sections processed, including ones sharing same description = {overview.count["new"] + overview.count["EXTRA_sections"]}\n"
    report += f"\t** Total number of sections output to csv = {overview.count["records_output"]}\n"
    missing = overview.missing["from_concordance"]
    missing_details = (
        # f" (record no.{"s" if len(missing) > 1 else ""}: {', '.join([str(el) for el in missing])})"
        f" (record no.{plural_s(len(missing))}: {', '.join([str(el) for el in missing])})"
        if len(missing)
        else ""
    )
    report += f"\t** Total number of sections without links in concordance: {len(missing)}{missing_details}\n"
    report += "\t" + ("*" * 73)
    return report


def plural_s(count):
    return "s" if count > 1 else ""


def update_text(outfile: Path, data: list[str], content:Content) -> None:
    """
    An attempt to update the file to add in the oid & onum
    """
    with outfile.open("w", encoding="utf-8") as f:
        ## print only first of a run of blank lines
        prev_was_blank = True
        for i, line in enumerate(data):
            if not line and prev_was_blank:
                continue
            elif not line:
                f.write(line + "\n")
                prev_was_blank = True
                continue
            else:
                prev_was_blank = False
            if re.match(r"@@\d", line):
                keys = line[2:].strip().split("&")
                oid, onum = [], []
                for key in keys:
                    oid.append(content.processed_sections[key].oid)
                    onum.append(content.processed_sections[key].onum)
                f.write("\n")
                f.write(f"@@NEW:{'&'.join(keys)}\n")
                f.write(f"@@OID:{'&'.join(oid)}\n")
                f.write(f"@@ONUM:{'&'.join(onum)}\n")
            else:
                f.write(line + "\n")


def main() -> None:
    text_dir = Path("text_files")
    csv_dir = Path("csv_files")
    concordance_file = Path("penny.concordance.xlsx")
    if concordance_file.with_suffix(".json").exists():
        concordance = shared.load_json_file(concordance_file.with_suffix(".json"))
    else:
        concordance = make_concordance_from_excel(concordance_file)
        shared.export_dict_to_json(concordance, concordance_file)
    if not csv_dir.exists():
        csv_dir.mkdir()
    update_dir = Path("updates")
    if not update_dir.exists():
        update_dir.mkdir()
    # concordance = make_concordance_from_excel("penny.concordance.xlsx")
    for source_file in text_dir.glob("*.txt"):
        overview.count.clear()
        overview.missing.clear()
        destination_file = csv_dir / f"{source_file.stem}.csv"
        updated_file = update_dir / f"{source_file.stem}.updated.txt"
        batch_name = source_file.stem
        logging.info(
            f"Reading from {source_file.name} and writing to {destination_file.name}..."
        )
        raw_lines: list[str] = shared.read_lines(source_file)
        content = process(raw_lines, concordance)
        content = apply_concordance(content, concordance)
        csv_ready_text = prepare_for_csv(content, batch_name)
        update_text(updated_file, raw_lines, content)
        del raw_lines
        logging.info(overview_report())
        # shared.write_csv(destination_file, csv_ready_text)
        shared.export_to_excel(destination_file, csv_ready_text)


if __name__ == "__main__":
    main()
